### PR TITLE
Quiz modal

### PR DESCRIPTION
**Pull request by gianlucastefanoni**

### CODE REVIEW

**Comment by ripa1995** [comment]
[Preview](https://runtimemachines-io-git-quiz-modal-runtime-machines.vercel.app/) is not working.

**Comment by gianlucastefanoni** [comment]
It doesn't work because the default website state is set to "serious" and not on "selection", we will change it in the prelanding page branch

**Review by Eliaxie — CHANGES_REQUESTED** [review]
fix the modal button css (also on mobile)

**Comment by Eliaxie** [comment]
mobile still broken @gianlucastefanoni

**Review by Eliaxie — APPROVED** [review]

**Pull request merged**
