### PR TITLE
feat: first two sides homepage

### PR DESCRIPTION
**Pull request by gianlucastefanoni**
Created a two-side homepage

### CODE REVIEW

**Review by Eliaxie — CHANGES_REQUESTED** [review]
- Try not to use inline-style css, it makes it very hard to manage when your CSS is in two separate places
- We were planning to use windicss, which is a CSS framework that allows you to write much less code, [take a look at this](https://tailwindcss.com/docs/utility-first) (this is a tailwind doc because they are compatible with each other and tailwind docs are a little bit more mature), this should make you go faster once you've familiarized with the sintax

**Comment by Eliaxie** [comment]
also, try to use TypeScript in your <script> tags,  it keeps it consistent with the frontmatter and allows you to write better quality, safer code :)

**Comment by ripa1995** [comment]
Few things:
- format code before pushing.
- assets (icon and logo), take the svg version without background, such that it can be resized in the code without loosing quality.

**Comment by Eliaxie** [comment]
bypassing fmt checks (we modified them in the dev branch)

**Review by Eliaxie — APPROVED** [review]

**Pull request merged**
