### PR TITLE
fixed windi style + part 2 refactoring

### PR DESCRIPTION
**Pull request by Eliaxie**

### CODE REVIEW

**Comment by Eliaxie** [comment]
this should be complete, tell me if I missed something @ripa1995

**Review by ripa1995 — APPROVED** [review]

**Comment by ripa1995** [comment]
There are still 2 raw color code usages in the game code. collision.js line 83/86 and game.js line 375

**Comment by Eliaxie** [comment]
The runner files are not parsed by windi nor astro, the only thing I can suggest is to move the colors to the config file


________________________________

**Comment by ripa1995** [comment]
> The runner files are not parsed by windi nor astro, the only thing I can suggest is to move the colors to the config file

If it is possible to have a css file in the same folder, then just move them inside it.

**Pull request merged**
